name: Build Binaries

on:
  release:
    types: 
      - created

jobs:
  build_for_mac_arm:
    name: MacOSArm
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install gdk-pixbuf pango gdk
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/peernet peernet-macos-arm64
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./peernet-macos-arm64
          asset_name: peernet-macos-arm64
          asset_content_type: application/octet-stream

  build_for_mac:
    name: MacOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install gdk-pixbuf pango gdk
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/peernet peernet-macos64
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./peernet-macos64
          asset_name: peernet-macos64
          asset_content_type: application/octet-stream

  build_for_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gdk-pixbuf2.0-dev libpango1.0-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/peernet peernet-linux-amd64 gdk-3.0
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./peernet-linux-amd64
          asset_name: peernet-linux-amd64
          asset_content_type: application/octet-stream
