name: Build Binaries

on:
  release:
    types: 
      - created

jobs:
  build_for_mac_arm:
    name: MacOSArm
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install gdk-pixbuf pango gtk+3 atkmm
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/PeerNet PeerNet-macos-arm64
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./PeerNet-macos-arm64
          asset_name: PeerNet-macos-arm64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build_for_mac:
    name: MacOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install gdk-pixbuf pango gtk+3 atkmm
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/PeerNet PeerNet-macos64
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./PeerNet-macos64
          asset_name: PeerNet-macos64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build_for_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gdk-pixbuf2.0-dev libpango1.0-dev libatk1.0-dev libgtk-3-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/PeerNet PeerNet-linux-amd64
      - name: Upload to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./PeerNet-linux-amd64
          asset_name: PeerNet-linux-amd64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build_for_windows:
    name: Build for Windows using Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build (Windows)
        run: docker-compose -f docker-compose.windows.yml up
      - name: Make Windows Installer
        run: ./create_windows_installer.sh
      - name: Zip Portable Windows Artifact
        run: zip -r windows-portable.zip package
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: executables
          path: |
            windows-portable.zip
            package/*.exe
